### PR TITLE
Remove cosmos keys dep

### PR DESCRIPTION
**Pull request by williamchong007**
image
(Based on #7) 
Instead of re-implementing the functions needed like in https://github.com/luniehq/cosmos-ledger/pull/4 , I noticed there is a useful function `getBech32FromPK ()` already exported from `ledger-cosmos-js`

### CODE REVIEW

**Comment by faboweb** [comment]
Nice finding!

**Comment by williamchong007** [comment]
@faboweb Just curious what is the release cycle of this package?
This PR would reduce gzip size by half and might be very useful for my project

**Comment by faboweb** [comment]
Doing a release tonight

**Comment by williamchong007** [comment]
I don't use (or at least not directly requires) `crypto-js` here so probably no such issue.

**Pull request merged**
